### ISSUE TITLE
Improve eyeless dog behaviour

### ISSUE THREAD

**Issue by Feiryn** [Feiryn/LethalMon#25]
Too situational as it is currently.
Make it as a mount that can attack

**Comment by Rea-XEVION** [comment]
when the eyeless pup of mine did nothing to distract a spider on exp, a hoarder bug on one assurance run, and a thumper on another assura run, I had to come and double check it's behavior here on the github because I thought either the dog or action keys were bugged.
 The spider and thumper both ran through the dogs model and nothing appeared to happen, while the hoarder bug flew over it's head four times as I went back and forth in front of a fire exit, hence why I had to double check the github for what the dog doin.
