### ISSUE TITLE
Improve the Baboon Hawk/Spider Behavior let the Mons be Lethal

### ISSUE THREAD

**Issue by ScottAust1n** [Feiryn/LethalMon#40]
https://github.com/user-attachments/assets/2dabc784-8dfc-4917-8634-7dab62f0a65f

The Baboon Hawks damage is too low, and Spiders should be able to attack similarly, if not more consistently. I am also not sure if the Baboon Hawk losing HP is intentional or not and having a death animation, so I am marking that as a bug.

**Comment by Feiryn** [comment]
The baboon and spiders are supports mons, it will be too OP if they deal a lot of damages, so it is intentional.
As for the HP, it is invisible and doesn't do anything so it's not a big deal.
For the baboon hawk animation, it idles and then sleep when it doesn't move for a while. It's not a death animation
